### PR TITLE
Create it.json

### PR DESCRIPTION
**Pull request by enryIT**

### CODE REVIEW

**Comment by Alexwijn** [comment]
Could I hang on to this pull request until the translations are final?

**Comment by Alexwijn** [comment]
Great, thanks!

**Comment by Alexwijn** [comment]
Could you update the pull request with the latest translations? I'll make sure it's added in a new release. Also note that I'm working on v2.0, can you maybe create a separate pull request for that branch? Thanks again!

**Comment by enryIT** [comment]
> Could you update the pull request with the latest translations? I'll make sure it's added in a new release. Also note that I'm working on v2.0, can you maybe create a separate pull request for that branch? Thanks again!

Done :D

**Pull request closed without merging**
